log:
  level: DEBUG

api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      middlewares:
        - redirect-to-https@file
  websecure:
    address: :443
  smtp:
    address: :25
  smtps:
    address: :465
  submission:
    address: :587

providers:
  file:
    filename: /etc/traefik/providers.yml
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: {{ env "LETSENCRYPT_EMAIL" | default "contact@example.com" }}
      storage: /certs/acme.json
      # use https://acme-staging-v02.api.letsencrypt.org/directory for staging
      caServer: {{ env "LETSENCRYPT_SERVER" | default "https://acme-v02.api.letsencrypt.org/directory" }}
      httpChallenge:
        entryPoint: web
