services:
    traefik:
        image: traefik:${TRAEFIK_VERSION:-3.1.2}
        container_name: ${PROJECT_NAME:-traefik}_traefik
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - TZ=${PROJECT_TZ:-Europe/Paris}
        networks:
            - ${PROJECT_NETWORK:-traefik}
        ports:
            - ${TRAEFIK_HTTP_PORT:-80}:80
            - ${TRAEFIK_HTTPS_PORT:-443}:443
            - ${TRAEFIK_SMTP_PORT:-25}:25
            - ${TRAEFIK_SMTPS_PORT:-465}:465
            - ${TRAEFIK_SUBMISSION_PORT:-587}:587
        labels:
            - traefik.enable=true
            - traefik.http.routers.${PROJECT_NAME:-traefik}_traefik.rule=Host(`${TRAEFIK_DASHBOARD_UI}`)
            - traefik.http.routers.${PROJECT_NAME:-traefik}_traefik.tls=true
            - traefik.http.routers.${PROJECT_NAME:-traefik}_traefik.service=api@internal
            - traefik.http.routers.${PROJECT_NAME:-traefik}_traefik.priority=998
            - traefik.http.routers.${PROJECT_NAME:-traefik}_traefik.tls.certresolver=letsencrypt
            - traefik.http.routers.${PROJECT_NAME:-traefik}_traefik.middlewares=basic-auth
            - traefik.http.middlewares.basic-auth.basicauth.users=${TRAEFIK_HTPASSWD_USER}:${TRAEFIK_HTPASSWD_PWD}

            - traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)
            - traefik.http.routers.http-catchall.entrypoints=web
            - traefik.http.routers.http-catchall.priority=999
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - .traefik/config/traefik-${PROJECT_ENV:-production}.yml:/etc/traefik/traefik.yml:ro
          - .traefik/config/providers.yml:/etc/traefik/providers.yml:ro
          - .traefik/certs:/certs

networks:
    ${PROJECT_NETWORK:-traefik}:
        external: true
